### PR TITLE
WIP: Testing teamserver

### PR DESCRIPTION
**Pull request by KoalaTea**
# Adding tests to teamserver and graphql

Fixes # (issue)
Does not fix an issue yet but is the start to it

# Test Plan

These are tests

### CODE REVIEW

**Comment by KoalaTea** [comment]
I do not understand why it has all of the ent as different. I have master merged into it.

**Comment by KCarretto** [comment]
@KoalaTea looks like test causes a nil-pointer dereference segfault. Can you verify this is a problem with the codebase and not the test case?
image

**Comment by KoalaTea** [comment]
I don't know how this happened it all passes on my machine which makes me "wat" will look into it see if I can reproduce

**Comment by KoalaTea** [comment]
oh these are from teamserver, I didn't fix up those tests yet. Graphql are worth looking at right now

**Pull request merged**
